version: '3.2'
services: 
  web: &web_base
    build: .
    image: english_learn_app:latests
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PORT: 3035
      WEBPACKER_DEV_SERVER_PUBLIC: webpacker:3035
    volumes:
      - .:/home/english_learn/app:rw

  webpacker:
    build: .
    image: english_learn_app:latests
    command: bash -c "rm -rf public/packs && ./bin/webpack-dev-server"
    volumes:
      - .:/home/english_learn/app:rw
    ports:
      - "3035:3035"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PORT: 3035
      WEBPACKER_DEV_SERVER_PUBLIC: webpacker:3035

  db: &db_base
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data:delegated




