
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") { "english_learn" } %>
  password: password

development:
  <<: *default
  database: englishLearn_development

test:
  <<: *default
  database: englishLearn_test

production:
  <<: *default
  database: englishLearn_production
  username: english_learn
  password: <%= ENV["ENGLISH_LEARN_DATABASE_PASSWORD"] %>
